INJECTION_PHRASES = [
    "ignore previous instructions",
    "disregard previous instructions",
    "system prompt",
    "developer message",
    "<system>",
    "begin system",
]

HIDDEN_INSTRUCTION_PHRASES = [
    "hidden instruction",
    "<instructions>",
    "do not tell the user",
    "secretly",
    "<!--",
    "-->",
    "\u200b",
    "\u200c",
    "\u200d",
]

CAPABILITY_KEYWORDS = {
    "MCPG-CAP-001": {
        "title": "shell execution capability",
        "capability": "shell_exec",
        "patterns": ["shell", "command", "terminal", "exec", "run_command"],
        "severity": "critical",
        "risk_score": 85,
        "risk_level": "L4",
        "policy_action": "deny",
    },
    "MCPG-CAP-002": {
        "title": "file read capability",
        "capability": "file_read",
        "patterns": ["read file", "file path", "filepath", "filesystem", "directory", ".env", ".ssh"],
        "severity": "high",
        "risk_score": 65,
        "risk_level": "L3",
        "policy_action": "require_approval",
    },
    "MCPG-CAP-003": {
        "title": "file write or destructive capability",
        "capability": "file_write",
        "patterns": ["write file", "delete file", "remove file", "move file", "overwrite", "delete"],
        "severity": "high",
        "risk_score": 70,
        "risk_level": "L3",
        "policy_action": "require_approval",
    },
    "MCPG-CAP-004": {
        "title": "network exfiltration capability",
        "capability": "network_send",
        "patterns": ["upload", "webhook", "post to", "send to", "exfiltrate", "leak"],
        "severity": "high",
        "risk_score": 70,
        "risk_level": "L3",
        "policy_action": "require_approval",
    },
    "MCPG-CAP-005": {
        "title": "browser automation capability",
        "capability": "browser_automation",
        "patterns": ["browser", "click", "navigate", "screenshot", "cookie"],
        "severity": "medium",
        "risk_score": 45,
        "risk_level": "L2",
        "policy_action": "allow_with_constraints",
    },
    "MCPG-CAP-006": {
        "title": "database access capability",
        "capability": "database_query",
        "patterns": ["sql", "database", "postgres", "mysql", "mongo"],
        "severity": "medium",
        "risk_score": 50,
        "risk_level": "L2",
        "policy_action": "allow_with_constraints",
    },
    "MCPG-CAP-007": {
        "title": "cloud api capability",
        "capability": "cloud_api",
        "patterns": ["aws", "gcp", "azure", "iam", "s3", "ec2", "kubernetes", "k8s"],
        "severity": "high",
        "risk_score": 65,
        "risk_level": "L3",
        "policy_action": "require_approval",
    },
    "MCPG-CAP-008": {
        "title": "messaging or email capability",
        "capability": "email_messaging",
        "patterns": ["email", "slack", "teams", "send_message", "message"],
        "severity": "high",
        "risk_score": 60,
        "risk_level": "L3",
        "policy_action": "require_approval",
    },
    "MCPG-CAP-009": {
        "title": "payment or purchase capability",
        "capability": "payment_purchase",
        "patterns": ["payment", "purchase", "checkout", "refund"],
        "severity": "critical",
        "risk_score": 85,
        "risk_level": "L4",
        "policy_action": "deny",
    },
}
